version: "3.9"  
services:
  web:
    container_name: fingu2.0
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860" 
    environment:
      - OPENAI_API_KEY=your_actual_openai_api_key 
